[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; Serial monitor
monitor_speed = 115200

; Partition scheme that includes LittleFS
board_build.partitions = min_spiffs.csv

; LittleFS filesystem upload
board_build.filesystem = littlefs

; Libraries
lib_deps =
    paulstoffregen/OneWire @ ^2.3.7
    milesburton/DallasTemperature @ ^3.11.0
    bblanchon/ArduinoJson @ ^7.0.4
    esp32 @ *               ; includes WiFi, HTTPClient, Update, LittleFS
